source "https://github.com/CocoaPods/Specs.git"
platform :ios, "8.0"
use_frameworks!

target "TCSwiftProjectDemo" do
pod 'SVProgressHUD'
pod 'SnapKit'
pod 'Kingfisher'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'WebViewJavascriptBridge', '~> 5.0'

end

